### ISSUE TITLE
Contract migration fails when run shortly after starting blockchain

### ISSUE THREAD

**Issue by julianboehm** [JacobEberhardt/decentralized-energy-trading#20]
When running `yarn migrate-contracts-authority` shortly after starting the Parity blockchain with Docker-Compose, the below error occurs.
At that moment, the monitor webpage shows that only node0 is on the latest block, while node1 and node2 seem to be still synchronizing.
The chance of this problem occurring increases if the blockchain has been running for a long time before restarting.

I resolved this by removing the Parity volume, effectively resetting the blockchain: `docker volume rm parity-authority_data-volume`
The error message is rather unintuitive, which is why I am documenting this here.

```
  Set verifier contract address ... 
Error: StatusError: Transaction: 0xee6cf63e26295088781ba8d93d7b8e3f3b15c87f5b2fe7adb68558d1898c6a71 exited with an error (status 0). 
     Please check that the transaction:
     - satisfies all conditions set by Solidity `require` statements.
     - does not trigger a Solidity `revert` statement.

    at Migration._deploy (/home/user/repo/node_modules/truffle/build/webpack:/packages/migrate/migration.js:124:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._load (/home/user/repo/node_modules/truffle/build/webpack:/packages/migrate/migration.js:54:1)
    at Migration.run (/home/user/repo/node_modules/truffle/build/webpack:/packages/migrate/migration.js:164:1)
```

**Comment by petscheit** [comment]
This is a know issue. I always wait for 10 blocks, thats my magic number. We're not really sure why this happens, my guess is, that the PoA algo takes a certain number of blocks to form consensus or something like that.
Quick way to delete the volume when shutting down the PoA chain is running `docker-compose down -v`
