### ISSUE TITLE
zoKratesCodeGenerator.js: billingPeriod missing in _updateAfterNettingDelta call

### ISSUE THREAD

**Issue by usdq777** [JacobEberhardt/decentralized-energy-trading#25]
**Branch: continuous-billing**

The zoKratesCodeGenerator currently generates a defective dUtility-Contract, because the billingPeriod is not included as an Input-Parameter in the _updateAfterNettingDelta Function Call in the checkHashes-Function.

![image](https://user-images.githubusercontent.com/51375009/77465115-73370200-6e08-11ea-86a0-d58376bbd7c6.png)

However, the _updateAfterNettingDelta-Function requires the billingPeriod:
![image](https://user-images.githubusercontent.com/51375009/77465256-9eb9ec80-6e08-11ea-86f4-f09dc3640791.png)

**Comment by julianboehm** [comment]
Does eb7fb25 fix this for you? (`continuous-billing` branch)
